apiVersion: v1
kind: Service
metadata:
  labels:
    de.metas.deployment.type: metasfresh-all-in-one
    de.metas.deployment.stage: "demo"
    de.metas.deployment.user: "tobi"
  name: "metasfresh-all-in-one-tobi-demo"
  namespace: default
spec:
  selector:
    de.metas.deployment.name: "metasfresh-all-in-one-tobi-demo"
  ports:
  - name: webapi
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: webui
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
# loadbalancer doesn't work with minikube
  #  type: LoadBalancer
  type: NodePort
status:
  loadBalancer: {}
